# Generated by Django 3.2.13 on 2022-06-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.CharField(max_length=5000)),
                ('stripe_secret_key', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Stripe Account Key',
                'verbose_name_plural': 'Stripe Account Key',
            },
        ),
    ]
