# Generated by Django 3.2.13 on 2022-06-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_instructor_auth_login'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Unpaid'), (1, 'Paid')], default=1)),
                ('name_prefix', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('learning_difficulty', models.BooleanField(default=False)),
                ('fast_track_test', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('previous_experience', models.IntegerField(choices=[(1, 'I had no lessons and i am not confident'), (2, 'I had no lessons but i am confident'), (3, 'I had 1-9 hours of driving lessons'), (4, 'I had 10-14 hours of driving lessons'), (5, 'I had 15-19 hours of driving lessons'), (6, 'I had 20-24 hours of driving lessons'), (7, 'I had 30 hours of driving lessons'), (8, 'I can drive at test standards, I want to retake')])),
                ('address', models.CharField(max_length=550)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistrationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_courses', to='portal.studentregistration')),
            ],
            options={
                'verbose_name': 'Student Registration Course',
                'verbose_name_plural': 'Student Registration Courses',
            },
        ),
    ]
