# Generated by Django 3.2.13 on 2022-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_studentregistration_studentregistrationcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
