# Generated by Django 3.2.13 on 2022-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20220623_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='total_intial_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True),
        ),
    ]
