# Generated by Django 3.2.13 on 2022-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_total_intial_deposit_studentregistration_total_initial_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid')], default=1),
        ),
    ]
