# Generated by Django 3.2.13 on 2022-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='advance_deposit',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=999),
            preserve_default=False,
        ),
    ]
