# Generated by Django 3.2.13 on 2022-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_course_advance_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='favicon',
            field=models.ImageField(default='default.jpg', upload_to='Favicons/'),
            preserve_default=False,
        ),
    ]
