# Generated by Django 3.2.13 on 2022-05-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_generalinfo_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageareacity',
            name='coverage_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='website.coveragearea'),
        ),
    ]
