# Generated by Django 3.2.13 on 2022-06-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_coverageareacity_coverage_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
