# Generated by Django 3.2.13 on 2022-06-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benifit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='Benifits')),
            ],
            options={
                'verbose_name': 'Benifit',
                'verbose_name_plural': 'Benifits',
            },
        ),
    ]
