# Generated by Django 3.2.13 on 2022-06-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_instructor_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unapproved'), (2, 'Approved')], default=1),
        ),
    ]
