# Generated by Django 3.2.13 on 2022-06-23 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_instructor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='auth_login',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_login', to=settings.AUTH_USER_MODEL),
        ),
    ]
